#!/bin/bash

# list aggregates for host/s

if [ "$1" = "-h" -o "$1" = "--help" -o "$1" = "-?" -o $# -lt 1 ]
then
  echo "usage: $(basename $0) <hostname...>"
  exit
fi

for h in $*
do
  echo -n "$h : "
  openstack hypervisor show -f json -c aggregates $(openstack hypervisor list -f value -c ID --matching ${h}) | jq -c '.[]'
done
